# Configuration for Alacritty, the GPU enhanced terminal emulator

[env]
# Environment variables
TERM = "xterm-256color"

[window]
# Transparency of the window (0.0 to 1.0)
opacity = 0.7

# Padding around the window (in pixels)
padding = { x = 10, y = 10 }

# Decorations for the window
# Options: "full", "none"
decorations = "none"

[font]
# Font configuration
normal = { family = "Fira Code Nerd Font", style = "Regular" }
bold = { family = "Fira Code Nerd Font", style = "Bold" }
italic = { family = "Fira Code Nerd Font", style = "Italic" }
bold_italic = { family = "Fira Code Nerd Font", style = "Bold Italic" }

# Font size
size = 12.0

[shell]
# Default shell program
program = "/usr/bin/fish"

[import]
# Path to color schemes or additional configs
paths = [
    "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]
